#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"
sudo service nginx start
