#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get update
sudo apt-get install haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 133148-web-01 100.26.138.159:80 check
   server 133148-web-02 54.174.108.229:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
