#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with
#+ a sleep 2 in between each iteration.
#	Displays "Iam invincible!!" in between each iteration.

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'each "I am invincible"' SIGTERM
done
